"""empty message

Revision ID: 21c0af58f9ca
Revises: 0b82b656bdd5
Create Date: 2020-11-13 18:52:55.149032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21c0af58f9ca'
down_revision = '0b82b656bdd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freerecipient', sa.Column('status', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('freerecipient', 'status')
    # ### end Alembic commands ###
