"""empty message

Revision ID: 2779243f9a0e
Revises: 21c0af58f9ca
Create Date: 2020-11-13 18:54:20.823501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2779243f9a0e'
down_revision = '21c0af58f9ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freerecipient', sa.Column('status', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('freerecipient', 'status')
    # ### end Alembic commands ###
