"""file_name and checksum to FreeNDA

Revision ID: 562507140cdb
Revises: f459eb050362
Create Date: 2020-12-09 20:32:19.579558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '562507140cdb'
down_revision = 'f459eb050362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('freenda', sa.Column('checksum', sa.String(length=200), nullable=True))
    op.add_column('freenda', sa.Column('file_name', sa.String(length=250), nullable=True))
    op.create_unique_constraint(None, 'freenda', ['checksum'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'freenda', type_='unique')
    op.drop_column('freenda', 'file_name')
    op.drop_column('freenda', 'checksum')
    # ### end Alembic commands ###
