"""empty message

Revision ID: 825928f832a3
Revises: 2779243f9a0e
Create Date: 2020-11-13 18:56:45.919136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '825928f832a3'
down_revision = '2779243f9a0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freerecipient', sa.Column('status', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('freerecipient', 'status')
    # ### end Alembic commands ###
