"""empty message

Revision ID: 92daf10fa034
Revises: 825928f832a3
Create Date: 2020-11-13 20:54:51.296913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92daf10fa034'
down_revision = '825928f832a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freefileshare', sa.Column('expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_freefileshare_expiration'), 'freefileshare', ['expiration'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_freefileshare_expiration'), table_name='freefileshare')
    op.drop_column('freefileshare', 'expiration')
    # ### end Alembic commands ###
