"""fiadded fields to FreeNDA model

Revision ID: e69bbab80f48
Revises: 562507140cdb
Create Date: 2020-12-11 12:29:58.625016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e69bbab80f48'
down_revision = '562507140cdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freenda', sa.Column('certificate_file_name', sa.String(length=250), nullable=True))
    op.add_column('freenda', sa.Column('certificate_file_url', sa.String(length=250), nullable=True))
    op.add_column('freenda', sa.Column('copy_emailed', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'freenda', ['checksum'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'freenda', type_='unique')
    op.drop_column('freenda', 'copy_emailed')
    op.drop_column('freenda', 'certificate_file_url')
    op.drop_column('freenda', 'certificate_file_name')
    # ### end Alembic commands ###
