"""ip_address and u user_agent to freeuselog

Revision ID: f459eb050362
Revises: 92daf10fa034
Create Date: 2020-12-09 15:15:42.925842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f459eb050362'
down_revision = '92daf10fa034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freeuselog', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('freeuselog', sa.Column('user_agent', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_freeuselog_ip_address'), 'freeuselog', ['ip_address'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_freeuselog_ip_address'), table_name='freeuselog')
    op.drop_column('freeuselog', 'user_agent')
    op.drop_column('freeuselog', 'ip_address')
    # ### end Alembic commands ###
